# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
import numpy as np

#### 2. Print your NumPy version.

In [80]:
np. __version__ 

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a=np.random.random((2,3,5))

In [11]:
a = np.random.randint(100, size=(2,3, 5))

In [28]:
a=np.random.random((2,3,5))
a

array([[[0.67470589, 0.54058369, 0.54337415, 0.1581671 , 0.21515498],
        [0.65268062, 0.15939581, 0.02650959, 0.28667973, 0.24670558],
        [0.79594641, 0.35479004, 0.12730754, 0.33529669, 0.52655789]],

       [[0.21724959, 0.55044294, 0.26597641, 0.08178621, 0.15406133],
        [0.06961714, 0.92214371, 0.3223537 , 0.32957537, 0.19198911],
        [0.1126341 , 0.015001  , 0.9918796 , 0.697669  , 0.59960866]]])

#### 4. Print *a*.


In [29]:
a

array([[[0.67470589, 0.54058369, 0.54337415, 0.1581671 , 0.21515498],
        [0.65268062, 0.15939581, 0.02650959, 0.28667973, 0.24670558],
        [0.79594641, 0.35479004, 0.12730754, 0.33529669, 0.52655789]],

       [[0.21724959, 0.55044294, 0.26597641, 0.08178621, 0.15406133],
        [0.06961714, 0.92214371, 0.3223537 , 0.32957537, 0.19198911],
        [0.1126341 , 0.015001  , 0.9918796 , 0.697669  , 0.59960866]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [30]:
b=np.ones((5,2,3))


#### 6. Print *b*.


In [31]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [42]:
np.shape(b)==np.shape(a)
print('They have the same number of elements but different shape')

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [33]:
print("no, they do not have the same matrix shape")

no, they do not have the same matrix notation


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [34]:
c=b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
d=a+c
d

array([[[1.67470589, 1.54058369, 1.54337415, 1.1581671 , 1.21515498],
        [1.65268062, 1.15939581, 1.02650959, 1.28667973, 1.24670558],
        [1.79594641, 1.35479004, 1.12730754, 1.33529669, 1.52655789]],

       [[1.21724959, 1.55044294, 1.26597641, 1.08178621, 1.15406133],
        [1.06961714, 1.92214371, 1.3223537 , 1.32957537, 1.19198911],
        [1.1126341 , 1.015001  , 1.9918796 , 1.697669  , 1.59960866]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
print('the rehaped matrix b has the same matrix shape as a')

the rehaped matrix b has the same matrix size as a


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [51]:
e==a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [77]:
f=np.empty((2,3,5))
np.shape(d)
np.shape(f)
d

array([[[1.67470589, 1.54058369, 1.54337415, 1.1581671 , 1.21515498],
        [1.65268062, 1.15939581, 1.02650959, 1.28667973, 1.24670558],
        [1.79594641, 1.35479004, 1.12730754, 1.33529669, 1.52655789]],

       [[1.21724959, 1.55044294, 1.26597641, 1.08178621, 1.15406133],
        [1.06961714, 1.92214371, 1.3223537 , 1.32957537, 1.19198911],
        [1.1126341 , 1.015001  , 1.9918796 , 1.697669  , 1.59960866]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [79]:
for i in d:
    for j in i:
        for x in j:
            if x>d_min and x< d_mean:
                f[np.where(d==x)]=25
            elif x>d_mean and x<d_max:
                f[np.where(d==x)]=75
            elif x== d_mean:
                f[np.where(d==x)]=50
            elif x==d_min:
                f[np.where(d==x)]=0
            elif x==d_max:
                f[np.where(d==x)]=100
f


array([[[ 75.,  75.,  75.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  75.]],

       [[ 25.,  75.,  25.,  25.,  25.],
        [ 25.,  75.,  25.,  25.,  25.],
        [ 25.,   0., 100.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here